modLoader="javafml" #mandatory

loaderVersion="[36,)"

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"

issueTrackerURL="https://github.com/Rojer-GH/TimeTravelMod/issues"
[[mods]]
modId="timetravelmod" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Time Travel Mod" #mandatory

# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/Rojer-GH/TimeTravelMod/wiki" #optional

# A file name (in the root of the mod JAR) containing a logo for display
# logoFile="examplemod.png" #optional

credits="https://github.com/Rojer-GH"

authors="It's me, who else? Nobody loves me..."

description='''
Insert your description here:
Just kidding, I'm lazy
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.timetravelmod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.timetravelmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"